# Generated by Django 4.1.5 on 2023-01-25 21:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=100, verbose_name='Brand Title')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Brand Image Name')),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Feature Name')),
            ],
            options={
                'verbose_name': 'Feature Name',
                'verbose_name_plural': 'Features Name',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=100)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values_of_feature', to='products.feature')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('summary_description', models.TextField(blank=True, default='', null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='Product Image Name')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Price')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is Active')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Product Name',
                'verbose_name_plural': 'Products Name',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='Group Title')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='ProductGroup Image Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is Active')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.productgroup', verbose_name='Parent Group')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Products Group',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='products.product', verbose_name='Product_Id')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='feature_id')),
                ('filter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features_of_value', to='products.featurevalue')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Products Features',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(through='products.ProductFeature', to='products.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_group', to='products.productgroup', verbose_name='Product Group'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product_group',
            field=models.ManyToManyField(related_name='feature_of_group', to='products.productgroup', verbose_name='Product Group'),
        ),
    ]
