# Generated by Django 4.1.5 on 2023-02-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={},
        ),
    ]
