# Generated by Django 4.1.5 on 2023-03-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_paymenttype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_state_title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'order state',
                'verbose_name_plural': 'order states',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderstate'),
        ),
    ]
