version: "3.8"
services:
  app:
    build: .
    volumes:
     - .:/django
    ports:
     - 8000:8000
    image: django:django
    container_name: django_container
    command: py manage.py runerver 0.0.0.0:8000