"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5&xh*gqqmdk)wg36qw5oy5yvmv70&o2$po0w$2#zh4v17q*vz#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []

# DEBUG = False                       # vaghti DEBUG false mishe dige error haro neshun nemide, page maro neshun mide. shop.py => urls.py => handler404. in baraye akhar kar ke project amade shod hast
# ALLOWED_HOSTS = ['*']               



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.main.apps.MainConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.products.apps.ProductsConfig",
    "apps.orders.apps.OrdersConfig",
    "apps.discount.apps.DiscountConfig",
    "apps.payments.apps.PaymentsConfig",
    "apps.warehouses.apps.WarehousesConfig",
    "apps.search.apps.SearchConfig",
    "apps.comment_scoring_favorites.apps.CommentScoringFavoritesConfig",
    "django_admin_listfilter_dropdown",
    "ckeditor",                                  # baraye upload text hast
    "ckeditor_uploader",                         # baraye upload text va file hast
    "django_render_partial",
    "django.contrib.humanize",                   # baraye comma dar 1,000,000 estefade mishe. 1. to inja ezafe kon 2. Dar file html aval load bad ba |intcomma estefade kon. see Products.html
    'django_filters',
    "rest_framework",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "middlewares.middlewares.RequestMiddleware",                # ezafe kardane middlewares baraye inke betunim request.user ro toye model estefade konim
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates/")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "apps.main.views.media_admin"                           # apps => main => views +> media_admin
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': "database1",
        "USER": "admin",
        "PASSWORD":"R4k_hector$",
        "HOST":"database-1.cfgce6640pvz.us-east-1.rds.amazonaws.com",
        "PORT":"3306",
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

#=================================================
# in ro bayad false kard
USE_TZ = False
#=================================================


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static/"),)



# Use Amazon S3 for storage for uploaded media files.
AWS_STORAGE_BUCKET_NAME = 'behzad-django-bucket'
AWS_ACCESS_KEY_ID = 'AKIAQLQCH7CVJQKEAY7F'
AWS_SECRET_ACCESS_KEY = 'HfO8EmMv1/NbGtkX/A+oaitrvQ7sBG3E3UQCWRqG'
AWS_S3_REGION_NAME = 'us-east-1'  # e.g., 'us-east-1'

# Use Amazon S3 for storage for uploaded media files.
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# User-uploaded files (media files)
MEDIA_URL = 'https://%s.s3.amazonaws.com/media/' % AWS_STORAGE_BUCKET_NAME
# MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#==============================================

# inja barash tarif kardim ke in User ro bejaye User default khodet run kon
AUTH_USER_MODEL="accounts.CustomUser"

#==============================================

# tanzimate ckeditor. mishe configs default estefade nakoni va modelhaye dige az internet biyari.
CKEDITOR_UPLOAD_PATH = "images/ckeditor/upload_files"
CKEDITOR_STORAGE_BACKEND= "django.core.files.storage.FileSystemStorage"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ]
    },
    'special': 
        {
            'toolbar': 'Special', 'height':500,
            'toolbar': 'full',
            'toolbar_Special':
            [
                ['Bold','Link','Unlink','Image'],
                ['CodeSnippet'],
            ], 'extraPlugins': ','.join(['codesnippet','clipboard', ])
    }
}

#==============================================