# Generated by Django 4.1.5 on 2023-02-24 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment_scoring_favorites', '0002_alter_comment_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approving_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approvedComments2', to=settings.AUTH_USER_MODEL, verbose_name='user approved comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.product'),
        ),
    ]
