# Generated by Django 4.1.5 on 2023-02-08 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_alter_customer_image_name'),
        ('orders', '0004_alter_paymenttype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tarikhe pardakht')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='tarikhe virayesh')),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('is_finally', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
