# Generated by Django 4.1.5 on 2023-05-10 18:24

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title1', models.CharField(blank=True, max_length=500, null=True, verbose_name='slider1')),
                ('slider_title2', models.CharField(blank=True, max_length=500, null=True, verbose_name='slider2')),
                ('slider_title3', models.CharField(blank=True, max_length=500, null=True, verbose_name='slider3')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('slider_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
